-- Vincula roles NAS (DB_NAS) con roles Intranet (BDJUNTOS.tbl_ctrl_usuarios_rol.iId)
IF COL_LENGTH('dbo.NASTM_ROLES', 'NU_ID_ROL_INTRANET') IS NULL
BEGIN
  ALTER TABLE dbo.NASTM_ROLES ADD NU_ID_ROL_INTRANET INT NULL;
END
GO

IF NOT EXISTS (
  SELECT 1 FROM sys.indexes
  WHERE name = N'UX_NASTM_ROLES_INTRANET' AND object_id = OBJECT_ID(N'dbo.NASTM_ROLES')
)
BEGIN
  CREATE UNIQUE INDEX UX_NASTM_ROLES_INTRANET ON dbo.NASTM_ROLES (NU_ID_ROL_INTRANET)
  WHERE NU_ID_ROL_INTRANET IS NOT NULL;
END
GO

-- Roles NAS (ajustar permisos en NASTD_ROLES_PERMISOS desde el admin del módulo)
MERGE dbo.NASTM_ROLES AS t
USING (VALUES
  (1072, N'NAS_ADMIN',     N'00 UTI - Admin NAS'),
  (1073, N'NAS_UCI',       N'00 UCI - NAS'),
  (1074, N'NAS_UAS',       N'00 UAS - NAS'),
  (1075, N'NAS_UOP',       N'00 UOP - NAS'),
  (1076, N'NAS_UTI',       N'00 UTI - NAS'),
  (1077, N'NAS_UA',        N'00 UA - NAS'),
  (1078, N'NAS_UI',        N'00 UI - NAS'),
  (1079, N'NAS_UPPM',      N'00 UPPM- NAS'),
  (1080, N'NAS_URH',       N'00 URH- NAS')
) AS s (NU_ID_ROL_INTRANET, NO_ROL, DE_ROL)
ON t.NU_ID_ROL_INTRANET = s.NU_ID_ROL_INTRANET
WHEN MATCHED THEN
  UPDATE SET NO_ROL = s.NO_ROL, DE_ROL = s.DE_ROL, FE_ACTUALIZACION = SYSUTCDATETIME()
WHEN NOT MATCHED THEN
  INSERT (NO_ROL, DE_ROL, IN_ES_SISTEMA, NU_ID_ROL_INTRANET)
  VALUES (s.NO_ROL, s.DE_ROL, 1, s.NU_ID_ROL_INTRANET);
GO

-- NAS_ADMIN hereda permisos de ADMIN legacy si existe
INSERT INTO dbo.NASTD_ROLES_PERMISOS (ID_ROL, ID_PERMISO)
SELECT na.ID_ROL, rp.ID_PERMISO
FROM dbo.NASTM_ROLES AS na
INNER JOIN dbo.NASTM_ROLES AS leg ON leg.NO_ROL = N'ADMIN'
INNER JOIN dbo.NASTD_ROLES_PERMISOS AS rp ON rp.ID_ROL = leg.ID_ROL
WHERE na.NO_ROL = N'NAS_ADMIN'
  AND NOT EXISTS (
    SELECT 1 FROM dbo.NASTD_ROLES_PERMISOS x
    WHERE x.ID_ROL = na.ID_ROL AND x.ID_PERMISO = rp.ID_PERMISO
  );
GO

-- Roles NAS operativos heredan permisos de USER legacy
INSERT INTO dbo.NASTD_ROLES_PERMISOS (ID_ROL, ID_PERMISO)
SELECT na.ID_ROL, rp.ID_PERMISO
FROM dbo.NASTM_ROLES AS na
INNER JOIN dbo.NASTM_ROLES AS leg ON leg.NO_ROL = N'USER'
INNER JOIN dbo.NASTD_ROLES_PERMISOS AS rp ON rp.ID_ROL = leg.ID_ROL
WHERE na.NO_ROL LIKE N'NAS_%' AND na.NO_ROL <> N'NAS_ADMIN'
  AND NOT EXISTS (
    SELECT 1 FROM dbo.NASTD_ROLES_PERMISOS x
    WHERE x.ID_ROL = na.ID_ROL AND x.ID_PERMISO = rp.ID_PERMISO
  );
GO
