-- Relación muchos-a-muchos: roles NAS ↔ categorías (unidades)
IF OBJECT_ID(N'dbo.NASTD_ROLES_CATEGORIAS', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.NASTD_ROLES_CATEGORIAS (
    ID_ROL UNIQUEIDENTIFIER NOT NULL,
    ID_CATEGORIA UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT PK_NASTD_ROLES_CATEGORIAS PRIMARY KEY (ID_ROL, ID_CATEGORIA),
    CONSTRAINT FK_NASTD_RC_ROL FOREIGN KEY (ID_ROL)
      REFERENCES dbo.NASTM_ROLES (ID_ROL) ON DELETE CASCADE,
    CONSTRAINT FK_NASTD_RC_CATEGORIA FOREIGN KEY (ID_CATEGORIA)
      REFERENCES dbo.NASTM_CATEGORIAS (ID_CATEGORIA) ON DELETE CASCADE
  );

  CREATE INDEX IDX_NASTD_RC_ID_ROL ON dbo.NASTD_ROLES_CATEGORIAS (ID_ROL);
  CREATE INDEX IDX_NASTD_RC_ID_CATEGORIA ON dbo.NASTD_ROLES_CATEGORIAS (ID_CATEGORIA);
END
GO

-- NAS operativos: NAS_{CODIGO} → categoría CO_CATEGORIA = {CODIGO}
INSERT INTO dbo.NASTD_ROLES_CATEGORIAS (ID_ROL, ID_CATEGORIA)
SELECT r.ID_ROL, c.ID_CATEGORIA
FROM dbo.NASTM_ROLES AS r
INNER JOIN dbo.NASTM_CATEGORIAS AS c
  ON c.CO_CATEGORIA = REPLACE(r.NO_ROL, N'NAS_', N'')
WHERE r.NO_ROL LIKE N'NAS_%'
  AND r.NO_ROL <> N'NAS_ADMIN'
  AND NOT EXISTS (
    SELECT 1 FROM dbo.NASTD_ROLES_CATEGORIAS AS x
    WHERE x.ID_ROL = r.ID_ROL AND x.ID_CATEGORIA = c.ID_CATEGORIA
  );
GO

-- NAS_ADMIN → todas las categorías vigentes
INSERT INTO dbo.NASTD_ROLES_CATEGORIAS (ID_ROL, ID_CATEGORIA)
SELECT r.ID_ROL, c.ID_CATEGORIA
FROM dbo.NASTM_ROLES AS r
CROSS JOIN dbo.NASTM_CATEGORIAS AS c
WHERE r.NO_ROL = N'NAS_ADMIN'
  AND (c.ES_VIGENTE = 1 OR c.ES_VIGENTE IS NULL)
  AND NOT EXISTS (
    SELECT 1 FROM dbo.NASTD_ROLES_CATEGORIAS AS x
    WHERE x.ID_ROL = r.ID_ROL AND x.ID_CATEGORIA = c.ID_CATEGORIA
  );
GO
