-- Políticas de subida por árbol de carpetas del propietario.
-- Ejecutar en DB_NAS. Sin filas => comportamiento histórico (acepta cualquier tipo; respeta tamaño ambiente/usuario).

USE DB_NAS;
GO

IF OBJECT_ID(N'dbo.NASTD_POLITICA_SUBIDA_EXENTOS', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.NASTD_POLITICA_SUBIDA_EXENTOS (
    ID_POLITICA UNIQUEIDENTIFIER NOT NULL,
    ID_USUARIO   UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT PK_POLITICA_EXENTO PRIMARY KEY (ID_POLITICA, ID_USUARIO)
  );
END
GO

IF OBJECT_ID(N'dbo.NASTM_CARPETA_POLITICA_SUBIDA', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.NASTM_CARPETA_POLITICA_SUBIDA (
    ID_POLITICA                    UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_POL_ID DEFAULT NEWSEQUENTIALID(),
    CONSTRAINT PK_NASTM_CARPETA_POLITICA_SUBIDA PRIMARY KEY (ID_POLITICA),
    ID_USUARIO_DUENO               UNIQUEIDENTIFIER NOT NULL,
    ID_CARPETA                     UNIQUEIDENTIFIER NULL,
    IN_PERMITE_FOTOS               BIT NOT NULL CONSTRAINT DF_POL_FOT DEFAULT 1,
    IN_PERMITE_VIDEOS              BIT NOT NULL CONSTRAINT DF_POL_VID DEFAULT 1,
    IN_PERMITE_DOCUMENTOS          BIT NOT NULL CONSTRAINT DF_POL_DOC DEFAULT 1,
    IN_PERMITE_OTROS               BIT NOT NULL CONSTRAINT DF_POL_OTR DEFAULT 1,
    IN_PERMITE_MULTIPLES           BIT NOT NULL CONSTRAINT DF_POL_MUL DEFAULT 1,
    CA_MAX_PESO_MB                 INT NULL,
    DE_EXTENSIONES_PERMITIDAS      NVARCHAR(500) NULL,
    FE_CREACION                    DATETIME2 NOT NULL CONSTRAINT DF_POL_FC DEFAULT SYSUTCDATETIME(),
    FE_ACTUALIZACION               DATETIME2 NOT NULL CONSTRAINT DF_POL_FA DEFAULT SYSUTCDATETIME()
  );

  ALTER TABLE dbo.NASTD_POLITICA_SUBIDA_EXENTOS ADD CONSTRAINT FK_POL_EXENTOS_POLITICA
    FOREIGN KEY (ID_POLITICA) REFERENCES dbo.NASTM_CARPETA_POLITICA_SUBIDA (ID_POLITICA) ON DELETE CASCADE;

  CREATE UNIQUE INDEX UX_POLITICA_SCOPE_CARPETA
    ON dbo.NASTM_CARPETA_POLITICA_SUBIDA (ID_USUARIO_DUENO, ID_CARPETA)
    WHERE ID_CARPETA IS NOT NULL;

  CREATE UNIQUE INDEX UX_POLITICA_SCOPE_DEFECTO
    ON dbo.NASTM_CARPETA_POLITICA_SUBIDA (ID_USUARIO_DUENO)
    WHERE ID_CARPETA IS NULL;
END
GO
