-- Baja lógica de categorías (unidades NAS). ES_VIGENTE = 0 → inactiva.

IF COL_LENGTH(N'dbo.NASTM_CATEGORIAS', N'ES_VIGENTE') IS NULL
BEGIN
    ALTER TABLE dbo.NASTM_CATEGORIAS ADD
        ES_VIGENTE BIT NOT NULL CONSTRAINT DF_NASTM_CAT_ES_VIGENTE DEFAULT 1;
END
GO
